### ISSUE TITLE
Testing of the Components

### ISSUE THREAD

**Issue by mikeshams** [lokeshchinthakuntla/Project#1]
Parth - What issues did you face when testing the components? How did you fix them?

**Comment by parthpatel10** [comment]
I had a problem when testing the LCD1602 display with the UNO Arduino ,when I built the circuit with the LCD screen and potentiometer., so the LCD screen was not displaying "Hello World" so I tried to re-check the circuit again and found out that the potentiometer was not adjusted at a point to where the brightness was visible.

**Comment by parthpatel10** [comment]
while testing a SIM800L GSM module i faced problem with power supply as some internet source mention that we can supply the board by connecting to Arduino 5v output using diode as diode drops 0.7v and we get 4.3v at the board. I tried with that and get over voltage warning through serial monitor while compiling code when i measured by DMM it was around 4.5v so i switched to the Lithium ion battery to power up the board.
