### ISSUE TITLE
Interfacing the WiFi Module

### ISSUE THREAD

**Issue by mikeshams** [lokeshchinthakuntla/Project#6]
Parth -  1) What issue did you have when interfacing the WiFi Module with the LPC1768? 2)How did you resolve them?

**Comment by parthpatel10** [comment]
while interfacing ESP8266 with LPC1768 I got the the interfacing code from mbed library which was compiling successfully but ESP was not able to make connection with home Wi-fi even nothing shown up on serial monitor to check what's going wrong. later I try with another code which use main.cpp file to work with all AT commands and to define UART pins without including any library file. while reviewing the code I found that this code also display available Wi-Fi network with their network strength and their connected status through serial monitor. After importing this code to main project file  ESP8266 works perfectly.
